# Generated by Django 5.1.3 on 2024-11-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия')),
                ('room_number', models.IntegerField(verbose_name='Номер комнаты')),
                ('room_area', models.FloatField(verbose_name='Площадь')),
                ('room_status', models.BooleanField(verbose_name='Статус')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('number_of_people', models.IntegerField(verbose_name='Кол-во человек')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Изображение')),
            ],
        ),
    ]
